# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CreditApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	
    pod 'Alamofire', '~> 4.4'
    pod 'SnapKit', '~> 4.2.0'
    pod 'XCGLogger' , '~> 6.0.4'
    pod 'SwiftyJSON', '~> 4.0'

    pod 'RxSwift',    '~> 4.3.0'
    pod 'RxCocoa',    '~> 4.3.0'
    pod 'RxBlocking',    '~> 4.3.0'
    pod 'Action'
    pod 'RxDataSources'

    pod 'AlamofireImage', '~> 3.4'
    pod 'Moya/RxSwift'
    pod 'ObjectMapper', '~> 3.3'
    pod 'AlamofireObjectMapper', '~> 5.0'
    pod 'RealmSwift'
    pod 'RxRealm'
    pod 'Charts'
    pod 'Kingfisher'

    pod 'ReachabilitySwift'
    
    pod 'MBProgressHUD'
    pod 'MWPhotoBrowser', :git => 'git@github.com:ZZZZou/MWPhotoBrowser.git'
  # Pods for CreditApp

    pod 'UMCCommon'
    pod 'UMCSecurityPlugins'
    pod 'UMCAnalytics'
    # U-Share SDK UI模块（分享面板，建议添加）
    pod 'UMCShare/UI'
    
    # 集成微信(精简版0.2M)
    pod 'UMCShare/Social/ReducedWeChat'
    
    # 集成QQ/QZone/TIM(精简版0.5M)
    pod 'UMCShare/Social/ReducedQQ'
    
    
    
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'RxSwift'
            target.build_configurations.each do |config|
                if config.name == 'Debug'
                    config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['-D', 'TRACE_RESOURCES']
                end
            end
        end
    end
end
